PROJECTS/task_manager_rails/config/routes.rb
Rails.application.routes.draw do
  get "tasks/table", to: "tasks#table", as: "table"
  root to: "tasks#index"
  resources :tasks
end

PROJECTS/task_manager_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

PROJECTS/task_manager_rails/app/models/task.rb
class Task < ApplicationRecord
end

PROJECTS/task_manager_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

PROJECTS/task_manager_rails/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[update show destroy edit]

  def create
    task = Task.create(task_params)

    redirect_to table_path, notice: "Your task is created!"
  end

  def update
    @task.update(task_params)

    redirect_to table_path, notice: "Task updated!"
  end

  def destroy
    @task.destroy

    redirect_to table_path, notice: "Task is deleted!"
  end

  def table
    @task = Task.all
  end

  def index
    @task = Task.all
  end

  def new
    @task = Task.new
  end

  def edit
  end

  private

  def task_params
    params.require(:task).permit(:body, :expiration_date, :user_id)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

PROJECTS/task_manager_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

PROJECTS/task_manager_rails/app/helpers/tasks_helper.rb
module TasksHelper
end

PROJECTS/task_manager_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagerRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <%if flash[:notice].present? %>
        <p class="message message-notice"><%=flash[:notice] %></p>
      <%end %>

      <%= yield %>
    </div>
  </body>
</html>

PROJECTS/task_manager_rails/app/views/tasks/edit.html.erb
<%=image_tag("pokemons.jpg", class: "background") %>

<div class="container" style="border-radius: 10px">
  <h2 class="title-lg mb">Redacting task</h2>

  <%= form_with model: @task do |form|%>
    <p style="margin-top: 10px"><%= form.label :body, "Content"%></p>
    <p><%= form.text_area :body, rows: 8, class: "form-text-area"%></p>

    <p class="mt"><%= form.label :expiration_date%></p>
    <p><%= form.text_field :expiration_date, class: "form-text-field"%></p>

    <p class="mt"><%= form.submit "Save", class: "button button-main"%></p>
  <%end%>
</div>

PROJECTS/task_manager_rails/app/views/tasks/index.html.erb
  <%=image_tag("pokemons.jpg", class: "background") %>

  <%date = Date.today%>
  <%beginning_of_week = date.beginning_of_week %>
  <%end_of_week = date.end_of_week %>

  <%week = (beginning_of_week..end_of_week).to_a %>

  <div class="container" style="border: 2px solid #131515; border-radius: 10px">

    <p class="title-md" style="text-align: center; font-size: 35px"> <%=(Time.new).strftime("%B").upcase %> </p>

    <div style="text-align: center; margin-top: 10px; margin-bottom: 15px">
      <%week.each do |element|%>
        <%if element.day == (Time.new).day.to_i %>
          <div class="item" style="background-color: #32CD32"> <%=element.day%></div>
        <%else %>
          <div class="item" style="background-color: #F0E68C"> <%=element.day%></div>
        <%end %>
      <% end %>
    </div>

    <div id="calendar_body">
      <%tasks = Task.where(expiration_date: (Time.new).strftime("%Y-%m-%d"))%>
      <%counter = 0 %>
      <ul>
      <%(tasks.size).times do%>
        <li style="word-break: break-all; border: 10px">
          <input type="checkbox" id="myCheckBox" style="margin: 15px"> <%="#{tasks[counter][:body]}"%>
        </li>
        <%counter += 1 %>
      <% end %>
      </ul>
    </div>

    <%if tasks.size == 0 %>
      <%result = "nothing to do..." %>
    <%else %>
      <%result = tasks.size %>
    <% end %>

    <div style="display: flex">
      <p style="margin-top: 15px; text-align: left; flex: 1"> <%= "Tasks on this day: #{result}" %> </p>
      <p class="mt">
        <%= button_to "Extended view", table_path, method: :get, class: "button button-main", style: "margin-top: 10px"%>
      </p>
    </div>

  </div>
</div>

PROJECTS/task_manager_rails/app/views/tasks/new.html.erb
<%=image_tag("pokemons.jpg", class: "background") %>

<div class="container" style="border-radius: 10px">
  <h2 class="title-lg mb">New task</h2>

  <%= form_with model: @task do |form|%>
    <p><%= form.label :body, "Text of task"%></p>
    <p><%= form.text_area :body, rows: 5, class: "form-text-area", required: true%></p>

    <p class="mt"><%= form.label :expiration_date%></p>
    <p><%= form.date_field :expiration_date, class: "form-text-area", required: true%></p>

    <p class="mt"><%= form.submit "Save", class: "button button-main"%></p>
  <%end%>
</div>

PROJECTS/task_manager_rails/app/views/tasks/table.html.erb
<div class="background">
  <%=image_tag("pokemons.jpg") %>
</div>

<div id="table_container">
  <div style="width: 900px; margin-bottom: 15px">
    <script async src="https://cse.google.com/cse.js?cx=54fb8eccee80946f2"></script>
    <div class="gcse-search"></div>
  </div>

  <div style="display: flex; align-items: center; margin-bottom: 25px">
    <div style="flex-grow: 1;">
      <p style="text-align: left; font-size: 20px"><%= link_to "back", tasks_path %></p>
    </div>
    <p class="title-lg mb" style="text-align: center; margin: 0;">Table of tasks</p>
    <div style="flex-grow: 1;"></div>
  </div>

  <%if @task.size == 0 %>
    <p style="text-align: center; margin-top: 15px; margin-bottom: 25px"><%="Table will be create after inputting data" %></p>
  <%else %>
    <table style="word-break: break-all">
      <tr>
        <th>№</th>
        <th>task text</th>
        <th>expiration date</th>
      </tr>

      <%id_table = 1 %>
      <%exception = Array.new %>
      <%@task.each do |task|%>
        <%if !exception.include?(task.expiration_date) %>
          <tr>
            <%examine_time = @task.where(expiration_date: task.expiration_date) %>

            <td style="width: 25px">
              <%="#{id_table}"%>
              <%id_table += 1 %>
            </td>

            <td>
              <%if (examine_time.size) > 1 %>
                <%counter = 0 %>
                <%examine_time.each do |item| %>
                  <h4><%="* #{item[:body]}"%> <%= link_to fa_icon("pencil"), edit_task_path(item.id), title: "Change task", style: "font-size: 18px"%> <%= button_to fa_icon("trash-o"), task_path(item.id), method: :delete, title: "Delete task", style: "font-size: 18px"%> </h4>
                  <%counter += 1 %>
                  <%if !exception.include?(task.expiration_date) %>
                    <%exception << examine_time[0][:expiration_date] %>
                  <%end %>
                <%end %>
              <%else %>
                <%="#{task.body}"%> <%= link_to fa_icon("pencil"), edit_task_path(task.id), title: "Change task", style: "font-size: 18px"%> <%= button_to fa_icon("trash-o"), task_path(task.id), method: :delete, title: "Delete task", style: "font-size: 18px"%>
              <%end %>
            </td>

            <td>
              <%="#{task.expiration_date}"%>
            </td>
          </tr>
        <%end %>
      <%end %>
    </table>
  <% end %>

  <p class="mt" style="text-align: center">
    <%= link_to "Add task", new_task_path, class: "button button-main"%>
  </p>
</div>